"""empty message

Revision ID: 001339562f5f
Revises: 766e45ad7299
Create Date: 2022-09-07 18:44:20.355983

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '001339562f5f'
down_revision = '766e45ad7299'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('user', sa.String(length=20), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'user')
    # ### end Alembic commands ###
