"""empty message

Revision ID: 9af99c539d36
Revises: 001339562f5f
Create Date: 2022-09-07 18:52:00.279660

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9af99c539d36'
down_revision = '001339562f5f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('user', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
